Рыбин Денис Юрьевич
Kostroma-Polytechnic-College/paper-io__3-1P9 pull request #8
Opened 2021-11-24 15:31 UTC by Bill44-NotAlone

Добавлен класс Coordinate, который вмещает в себя координаты объекта.
Создана функция для создания игроков в случае если есть пустая территория размером 3 на 3 (StartGame). Добавлена вспомогательная функция, определяющая возможно ли поместить матрицу 3 на 3 в подматрицу (ChekPoint). Создана доп. функция, которая создает игрока в центре матрицы (CreatePlayer).
Доработан класс Player.
Разнес по файлам, как мог. :)

2021-11-26 06:12 UTC, YuriSilenok requested changes

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Coordinate.cs
> +    }
Используйте стандартную структуру Point

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +        private Player[,] gamematrix; //Кол-во игроков
Это явно не количество игроков и комментарий сделан не правильно

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +        int heightmatrix;
зачем нам хранить это в классе, это по сути количество игроков, которое можно получить из списка игроков, которого в этом классе нет. Так что это придется убрать, когда появится список игроков

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +            //int[строка , столбец]
правильно оформите комментарий

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +            List<Coordinate> coordinates = new List<Coordinate>();
Почему нужно работать со списком координат? Ты ведь ищешь одну координату свободного места, а потом уже создаешь игрока

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +                        if (gamematrix[l, c] != null) return (false);
`(false)` скобки не нужны

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +                for (int column = 0; column < heightmatrix; column++)
нет смысла просматривать два последних столбца

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +            }
лучше правильно написать цикл, вызывающий функцию, чем обрабатывать исключение выхода за границу массива

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +        public void StartGame()
Я думаю этот метод должен вызываться из конструктора при создании игры.

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Game.cs
> +            Player player = new Player(new Coordinate(coordinate.X + 1, coordinate.Y + 1));
А почему игрок не добавляется в список игроков?

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/MainWindow.xaml.cs
> +﻿using System.Windows;
уверен что нужно было все это удалять?

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Player.cs
> +        private Color colorOfPlayer; //Негр?
нужны правильные комментарии

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Player.cs
> +        public Player(Coordinate сoordinate, bool Life, Color color)
можно создать мертвого игрока и тот кто создает игрока определяет его цвет, может быть выбор цвета это внутренний механизм?

2021-11-26 06:12 UTC, YuriSilenok commented on paper-io/Player.cs
> +        }
а как же цвет и жизнь?

2021-11-26 06:23 UTC, Bill44-NotAlone commented on paper-io/Game.cs
> +        private Player[,] gamematrix; //Кол-во игроков
Матрицу не я создавал.

2021-11-26 06:25 UTC, Bill44-NotAlone commented on paper-io/Game.cs
> +        int heightmatrix;
Это не количество игроков, а размерность матрицы. Но добавлю список.

2021-11-26 06:39 UTC, Bill44-NotAlone commented on paper-io/Game.cs
> +            //int[строка , столбец]
Косяк. Этого комментария в принципе не должно существовать.

2021-11-26 06:40 UTC, Bill44-NotAlone commented on paper-io/Game.cs
> +            List<Coordinate> coordinates = new List<Coordinate>();
Сначала я ищу все возможные варианты генерации игрока, если такие найдутся, то выбираем одну координату и создаем игрока.

2021-11-26 06:41 UTC, Bill44-NotAlone commented on paper-io/MainWindow.xaml.cs
> +﻿using System.Windows;
Пока они не тербуются.

2021-11-26 06:43 UTC, Bill44-NotAlone commented on paper-io/Player.cs
> +        }
Добавлю.

2021-11-26 06:45 UTC, Bill44-NotAlone commented on paper-io/Coordinate.cs
> +    }
Преобразую.

2021-11-26 07:45 UTC, Bill44-NotAlone commented on paper-io/Game.cs
> +                        if (gamematrix[l, c] != null) return (false);
Знаю, но пусть будут.

2021-11-28 18:48 UTC, YuriSilenok commented
А чего закрыл пулл реквест?

2021-11-28 18:52 UTC, YuriSilenok commented on paper-io/Game.cs
> +        int heightmatrix;
Размерность матрицы можно получить методом GetLength

2021-11-28 18:53 UTC, YuriSilenok commented on paper-io/Game.cs
> +        public void StartGame()
А еще название метода не соответствует его содержимому

2021-11-28 19:01 UTC, YuriSilenok requested changes
Вообще, в программировании для обозначения координат чего либо используют слово location, а не coordinate

2021-11-28 19:01 UTC, YuriSilenok commented on paper-io/Game.cs
> +                Point coordinate = coordinates[random.Next(0, coordinates.Count() - 1)];
`[random.Next(0, coordinates.Count() - 1)`
- 0 не обязательно указывать
- -1 не нужно указывать

2021-11-28 19:01 UTC, YuriSilenok commented on paper-io/Game.cs
> +                        if (gamematrix[l, c] != null) return (false);
Мой аргумент, это засоряет код, а Ваш?

2021-11-28 19:01 UTC, YuriSilenok commented on paper-io/Game.cs
> +            }
с чем связано здесь появление обработчика исключений?

2021-11-28 19:01 UTC, YuriSilenok commented on paper-io/MainWindow.xaml.cs
> +﻿using System.Windows;
Такой рефакторинг проводят когда форма готова, иначе не опытные разработчики не смогу понять, почему у них классы не работают.

2021-11-28 19:01 UTC, YuriSilenok commented on paper-io/Player.cs
> +        private int y;
Может Location типа Point?

2021-11-28 19:01 UTC, YuriSilenok commented on paper-io/Player.cs
> +        }
Если кто-то что-то лишнее сделал или сделал не так, попросите его исправить или уберите сами. но не нужно засорять код старым кодом в комментариях

2021-12-06 05:35 UTC, Bill44-NotAlone commented on paper-io/Game.cs
> +        public void StartGame()
Лучше сделать все же разделение. Это на тот случай, если мы действительно создадим игру с другими игроками. Мы же не будим создавать n-ной кол-во игр, а создадим 1 полет? А через метод его отобразим. Я, честно говоря не знаю. Я верно думаю?
Я не мастер креативных названий. Назвал я функцию так, потому что с точки зрения конкретного игрока эта функция - действительно начало игры. Я ее могу назвать "StartGameForPlayer", а не назвал, потому что не увидел просьбы и теперь оправдываюсь.

2021-12-06 05:45 UTC, YuriSilenok commented on paper-io/Player.cs
> +        private Point point;
Используйте слово Location

2021-12-06 05:45 UTC, YuriSilenok commented on paper-io/Player.cs
> +        public Player(Point coordinate)
location

2021-12-10 05:43 UTC, YuriSilenok requested changes

2021-12-10 05:43 UTC, YuriSilenok commented on paper-io/MainWindow.xaml.cs
> +﻿using System.Windows;
Замечание не исправлено

2021-12-10 05:43 UTC, YuriSilenok commented on paper-io/Game.cs
> +        /// Создает матрицу 3 на 3 с игроком в центре.
Этот метод не создает матрицу

2021-12-10 05:43 UTC, YuriSilenok commented on paper-io/Game.cs
> +        /// Создает матрицу 3 на 3 с игроком в центре.
комментарий + название метода

2021-12-10 05:43 UTC, YuriSilenok commented on paper-io/Player.cs
> +        }
удалить

2021-12-10 05:43 UTC, YuriSilenok commented on paper-io/Player.cs
> +        public Player(Point coordinate)
или point

2021-12-10 06:07 UTC, YuriSilenok requested changes

2021-12-10 06:07 UTC, YuriSilenok commented on paper-io/Game.cs
> +        public void CheckingMatrixForVoidness()
Это не проверка, а поиск

2021-12-10 06:07 UTC, YuriSilenok commented on paper-io/Game.cs
> +        /// Проверяе, входит ли подматрица 3 на 3, начиная с верхнего левого угла.
ееее

2021-12-10 06:07 UTC, YuriSilenok commented on paper-io/Game.cs
> +using System.Windows.Shapes;
это здесь не нужно

2021-12-10 06:07 UTC, YuriSilenok commented on paper-io/Player.cs
> +using System.Windows.Shapes;
это здесь не нужно

2021-12-10 06:28 UTC, YuriSilenok approved these changes

2021-12-10 06:28 UTC, merged